=== ferdisap/mpub/assets/schemas/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="qualified"
  elementFormDefault="qualified">
  <xs:element name="config" type="configElemType"/>
  <xs:complexType name="configElemType">
    <xs:sequence>
      <xs:element name="output" type="outputElemType"/>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="layout" type="layoutElemType"/>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="outputElemType">
    <xs:sequence>
      <xs:element name="method" type="methodElemType" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="layoutElemType">
    <xs:choice>
      <xs:element name="simple-page-master" type="simplePageMasterElemType" maxOccurs="unbounded" minOccurs="0"/>
    </xs:choice>
    <xs:attribute name="master-name" use="required" type="xs:string"/>
    <xs:attribute ref="type" use="required"/>
    <xs:attribute name="length-unit" type="lengthUnitAttType"/>
    <xs:attribute name="area-unit" type="areaUnitAttType"/>
    <xs:attribute name="width" use="required" type="xs:double"/>
    <xs:attribute name="height" use="required" type="xs:double"/>
    <xs:attribute name="default-font-size" type="xs:integer"/>
    <xs:attribute name="cgmark-offset" use="required" type="xs:double"/>
    <xs:attribute name="start-indent" use="required" type="xs:double"/>
    <xs:attribute name="orientation" type="orientationAttType"/>
  </xs:complexType>
  <xs:complexType name="simplePageMasterElemType">
    <xs:sequence>
      <!-- for odd -->
      <xs:element name="master-name_for_odd" type="xs:string"/>
      <xs:element name="margin-top_for_odd" type="xs:double"/>
      <xs:element name="margin-bottom_for_odd" type="xs:double"/>
      <xs:element name="margin-left_for_odd" type="xs:double"/>
      <xs:element name="margin-right_for_odd" type="xs:double"/>
      <xs:element name="margin-top_for_odd_body" type="xs:double"/>
      <xs:element name="margin-bottom_for_odd_body" type="xs:double"/>
      <xs:element name="margin-left_for_odd_body" type="xs:double"/>
      <xs:element name="margin-right_for_odd_body" type="xs:double"/>
      <xs:element name="extent_for_odd_header" type="xs:double"/>
      <xs:element name="extent_for_odd_footer" type="xs:double"/>
      <!-- for even -->
      <xs:element name="master-name_for_even" type="xs:string"/>
      <xs:element name="margin-top_for_even" type="xs:double"/>
      <xs:element name="margin-bottom_for_even" type="xs:double"/>
      <xs:element name="margin-left_for_even" type="xs:double"/>
      <xs:element name="margin-right_for_even" type="xs:double"/>
      <xs:element name="margin-top_for_even_body" type="xs:double"/>
      <xs:element name="margin-bottom_for_even_body" type="xs:double"/>
      <xs:element name="margin-left_for_even_body" type="xs:double"/>
      <xs:element name="margin-right_for_even_body" type="xs:double"/>
      <xs:element name="extent_for_even_header" type="xs:double"/>
      <xs:element name="extent_for_even_footer" type="xs:double"/>
      <!-- for left blank -->
      <xs:element name="master-name_for_leftBlank" type="xs:string"/>
      <xs:element name="margin-top_for_leftBlank" type="xs:double"/>
      <xs:element name="margin-bottom_for_leftBlank" type="xs:double"/>
      <xs:element name="margin-left_for_leftBlank" type="xs:double"/>
      <xs:element name="margin-right_for_leftBlank" type="xs:double"/>
      <xs:element name="margin-top_for_leftBlank_body" type="xs:double"/>
      <xs:element name="margin-bottom_for_leftBlank_body" type="xs:double"/>
      <xs:element name="margin-left_for_leftBlank_body" type="xs:double"/>
      <xs:element name="margin-right_for_leftBlank_body" type="xs:double"/>
      <xs:element name="extent_for_leftBlank_header" type="xs:double"/>
      <xs:element name="extent_for_leftBlank_footer" type="xs:double"/>
      <!-- for region name -->
      <xs:element name="region-name_for_body" type="xs:string"/>
      <xs:element name="region-name_for_bodyLeftBlank" type="xs:string"/>
      <xs:element name="region-name_for_headerOdd" type="xs:string"/>
      <xs:element name="region-name_for_footerOdd" type="xs:string"/>
      <xs:element name="region-name_for_headerEven" type="xs:string"/>
      <xs:element name="region-name_for_footerEven" type="xs:string"/>
      <xs:element name="region-name_for_headerLeftBlank" type="xs:string"/>
      <xs:element name="region-name_for_footerLeftBlank" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="lengthUnitAttType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="cm"/>
      <xs:enumeration value="mm"/>
      <xs:enumeration value="%"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="areaUnitAttType">
    <xs:restriction base="xs:NMTOKEN">
      <xs:enumeration value="pt"/>
      <xs:enumeration value="px"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="orientationAttType">
    <xs:restriction base="xs:NMTOKEN">
      <xs:enumeration value="land"/>
      <xs:enumeration value="port"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="methodElemType">
    <xs:sequence>
      <xs:element name="path" type="pathElemType"/>
    </xs:sequence>
    <xs:attribute ref="type" use="required"/>
  </xs:complexType>
  <xs:complexType name="pathElemType" mixed="true">
    <xs:attribute name="product-name" use="required"/>
  </xs:complexType>
  <xs:attribute name="type">
    <xs:simpleType>
      <xs:restriction base="xs:NMTOKEN">
        <xs:enumeration value="pdf"/>
        <xs:enumeration value="html"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>
  
</xs:schema>

=== ferdisap/mpub/src/Config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- perbaiki xsl nya
  attribute @cgmark-offset sudah tidak ada unit satuannya
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../assets/schemas/config.xsd">
  <output>
    <method type="pdf">
      <path product-name="*">../Transformer/xsl/pdf/CN235/Main.xsl</path>
      <path product-name="CN235">../Transformer/xsl/pdf/CN235/Main.xsl</path>
      <path product-name="assets">../Transformer/xsl/pdf/assets</path>
    </method>
    <method type="html">
      <path product-name="*">./index.xsl</path>
    </method>
  </output>
  <layout type="pdf" master-name="default-A4L" length-unit="cm" area-unit="pt" width="29.7" height="21" default-font-size="11" cgmark-offset="0.5" start-indent="1.5" orientation="land">
    <simple-page-master>
      <master-name_for_odd>odd</master-name_for_odd>
      <margin-top_for_odd>3</margin-top_for_odd>
      <margin-bottom_for_odd>1.5</margin-bottom_for_odd>
      <margin-left_for_odd>2</margin-left_for_odd>
      <margin-right_for_odd>1</margin-right_for_odd>
      <margin-top_for_odd_body>0</margin-top_for_odd_body>
      <margin-bottom_for_odd_body>0</margin-bottom_for_odd_body>
      <margin-left_for_odd_body>1</margin-left_for_odd_body>
      <margin-right_for_odd_body>1</margin-right_for_odd_body>
      <extent_for_odd_header>0.5</extent_for_odd_header>
      <extent_for_odd_footer>-1.5</extent_for_odd_footer>

      <master-name_for_even>even</master-name_for_even>
      <margin-top_for_even>1.5</margin-top_for_even>
      <margin-bottom_for_even>3</margin-bottom_for_even>
      <margin-left_for_even>2</margin-left_for_even>
      <margin-right_for_even>1</margin-right_for_even>
      <margin-top_for_even_body>0</margin-top_for_even_body>
      <margin-bottom_for_even_body>0</margin-bottom_for_even_body>
      <margin-left_for_even_body>1</margin-left_for_even_body>
      <margin-right_for_even_body>1</margin-right_for_even_body>
      <extent_for_even_header>0.5</extent_for_even_header>
      <extent_for_even_footer>-1.5</extent_for_even_footer>

      <master-name_for_leftBlank>left-blank</master-name_for_leftBlank>
      <margin-top_for_leftBlank>1</margin-top_for_leftBlank>
      <margin-bottom_for_leftBlank>1</margin-bottom_for_leftBlank>
      <margin-left_for_leftBlank>1.5</margin-left_for_leftBlank>
      <margin-right_for_leftBlank>3</margin-right_for_leftBlank>
      <margin-top_for_leftBlank_body>1.5</margin-top_for_leftBlank_body>
      <margin-bottom_for_leftBlank_body>2</margin-bottom_for_leftBlank_body>
      <margin-left_for_leftBlank_body>0</margin-left_for_leftBlank_body>
      <margin-right_for_leftBlank_body>0</margin-right_for_leftBlank_body>
      <extent_for_leftBlank_header>1.5</extent_for_leftBlank_header>
      <extent_for_leftBlank_footer>2</extent_for_leftBlank_footer>

      <region-name_for_body>body</region-name_for_body>
      <region-name_for_bodyLeftBlank>left_blank</region-name_for_bodyLeftBlank>
      <region-name_for_headerOdd>header-odd</region-name_for_headerOdd>
      <region-name_for_footerOdd>footer-odd</region-name_for_footerOdd>
      <region-name_for_headerEven>header-even</region-name_for_headerEven>
      <region-name_for_footerEven>footer-even</region-name_for_footerEven>
      <region-name_for_headerLeftBlank>header-left_blank</region-name_for_headerLeftBlank>
      <region-name_for_footerLeftBlank>footer-left_blank</region-name_for_footerLeftBlank>
    </simple-page-master>
  </layout>
  <layout type="pdf" master-name="default-A4" length-unit="cm" area-unit="pt" width="21" height="29.7" default-font-size="11" cgmark-offset="2" start-indent="1.5" orientation="port">
    <simple-page-master>
      <master-name_for_odd>odd</master-name_for_odd>
      <margin-top_for_odd>1</margin-top_for_odd>
      <margin-bottom_for_odd>1</margin-bottom_for_odd>
      <margin-left_for_odd>3</margin-left_for_odd>
      <margin-right_for_odd>1.5</margin-right_for_odd>
      <margin-top_for_odd_body>1.5</margin-top_for_odd_body>
      <margin-bottom_for_odd_body>1.7</margin-bottom_for_odd_body>
      <margin-left_for_odd_body>0</margin-left_for_odd_body>
      <margin-right_for_odd_body>0</margin-right_for_odd_body>
      <extent_for_odd_header>1.5</extent_for_odd_header>
      <extent_for_odd_footer>1.5</extent_for_odd_footer>

      <master-name_for_even>even</master-name_for_even>
      <margin-top_for_even>1</margin-top_for_even>
      <margin-bottom_for_even>1</margin-bottom_for_even>
      <margin-left_for_even>1.5</margin-left_for_even>
      <margin-right_for_even>3</margin-right_for_even>
      <margin-top_for_even_body>1.5</margin-top_for_even_body>
      <margin-bottom_for_even_body>1.7</margin-bottom_for_even_body>
      <margin-left_for_even_body>0</margin-left_for_even_body>
      <margin-right_for_even_body>0</margin-right_for_even_body>
      <extent_for_even_header>1.5</extent_for_even_header>
      <extent_for_even_footer>1.5</extent_for_even_footer>

      <master-name_for_leftBlank>left-blank</master-name_for_leftBlank>
      <margin-top_for_leftBlank>1</margin-top_for_leftBlank>
      <margin-bottom_for_leftBlank>1</margin-bottom_for_leftBlank>
      <margin-left_for_leftBlank>1.5</margin-left_for_leftBlank>
      <margin-right_for_leftBlank>3</margin-right_for_leftBlank>
      <margin-top_for_leftBlank_body>1.5</margin-top_for_leftBlank_body>
      <margin-bottom_for_leftBlank_body>2</margin-bottom_for_leftBlank_body>
      <margin-left_for_leftBlank_body>0</margin-left_for_leftBlank_body>
      <margin-right_for_leftBlank_body>0</margin-right_for_leftBlank_body>
      <extent_for_leftBlank_header>1.5</extent_for_leftBlank_header>
      <extent_for_leftBlank_footer>2</extent_for_leftBlank_footer>

      <region-name_for_body>body</region-name_for_body>
      <region-name_for_bodyLeftBlank>left_blank</region-name_for_bodyLeftBlank>
      <region-name_for_headerOdd>header-odd</region-name_for_headerOdd>
      <region-name_for_footerOdd>footer-odd</region-name_for_footerOdd>
      <region-name_for_headerEven>header-even</region-name_for_headerEven>
      <region-name_for_footerEven>footer-even</region-name_for_footerEven>
      <region-name_for_headerLeftBlank>header-left_blank</region-name_for_headerLeftBlank>
      <region-name_for_footerLeftBlank>footer-left_blank</region-name_for_footerLeftBlank>
    </simple-page-master>
  </layout>
  <layout type="pdf" master-name="default-pm" length-unit="cm" area-unit="pt" width="21" height="29.7" default-font-size="11" cgmark-offset="2" start-indent="1.5" orientation="port">
    <simple-page-master>
      <master-name_for_odd>oddA4</master-name_for_odd>
      <margin-top_for_odd>1</margin-top_for_odd>
      <margin-bottom_for_odd>1</margin-bottom_for_odd>
      <margin-left_for_odd>3</margin-left_for_odd>
      <margin-right_for_odd>1.5</margin-right_for_odd>
      <margin-top_for_odd_body>1.5</margin-top_for_odd_body>
      <margin-bottom_for_odd_body>1.7</margin-bottom_for_odd_body>
      <margin-left_for_odd_body>0</margin-left_for_odd_body>
      <margin-right_for_odd_body>0</margin-right_for_odd_body>
      <extent_for_odd_header>1.5</extent_for_odd_header>
      <extent_for_odd_footer>1.5</extent_for_odd_footer>

      <master-name_for_even>evenA4</master-name_for_even>
      <margin-top_for_even>1</margin-top_for_even>
      <margin-bottom_for_even>1</margin-bottom_for_even>
      <margin-left_for_even>1.5</margin-left_for_even>
      <margin-right_for_even>3</margin-right_for_even>
      <margin-top_for_even_body>1.5</margin-top_for_even_body>
      <margin-bottom_for_even_body>1.7</margin-bottom_for_even_body>
      <margin-left_for_even_body>0</margin-left_for_even_body>
      <margin-right_for_even_body>0</margin-right_for_even_body>
      <extent_for_even_header>1.5</extent_for_even_header>
      <extent_for_even_footer>1.5</extent_for_even_footer>

      <master-name_for_leftBlank>left-blankA4</master-name_for_leftBlank>
      <margin-top_for_leftBlank>1</margin-top_for_leftBlank>
      <margin-bottom_for_leftBlank>1</margin-bottom_for_leftBlank>
      <margin-left_for_leftBlank>1.5</margin-left_for_leftBlank>
      <margin-right_for_leftBlank>3</margin-right_for_leftBlank>
      <margin-top_for_leftBlank_body>1.5</margin-top_for_leftBlank_body>
      <margin-bottom_for_leftBlank_body>2</margin-bottom_for_leftBlank_body>
      <margin-left_for_leftBlank_body>0</margin-left_for_leftBlank_body>
      <margin-right_for_leftBlank_body>0</margin-right_for_leftBlank_body>
      <extent_for_leftBlank_header>1.5</extent_for_leftBlank_header>
      <extent_for_leftBlank_footer>2</extent_for_leftBlank_footer>

      <region-name_for_body>body</region-name_for_body>
      <region-name_for_bodyLeftBlank>left_blank</region-name_for_bodyLeftBlank>
      <region-name_for_headerOdd>header-odd</region-name_for_headerOdd>
      <region-name_for_footerOdd>footer-odd</region-name_for_footerOdd>
      <region-name_for_headerEven>header-even</region-name_for_headerEven>
      <region-name_for_footerEven>footer-even</region-name_for_footerEven>
      <region-name_for_headerLeftBlank>header-left_blank</region-name_for_headerLeftBlank>
      <region-name_for_footerLeftBlank>footer-left_blank</region-name_for_footerLeftBlank>
    </simple-page-master>
  </layout>
  <layout type="pdf" master-name="poh" length-unit="cm" area-unit="pt" width="14.8" height="21" default-font-size="10" cgmark-offset="2" start-indent="1.5" orientation="port">
    <simple-page-master>
      <master-name_for_odd>oddA5_poh</master-name_for_odd>
      <margin-top_for_odd>1</margin-top_for_odd>
      <margin-bottom_for_odd>1</margin-bottom_for_odd>
      <margin-left_for_odd>2</margin-left_for_odd>
      <margin-right_for_odd>1</margin-right_for_odd>
      <margin-top_for_odd_body>1.5</margin-top_for_odd_body>
      <margin-bottom_for_odd_body>1.2</margin-bottom_for_odd_body>
      <margin-left_for_odd_body>0</margin-left_for_odd_body>
