=== ferdisap/mpub/assets/schemas/interpretation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="qualified" elementFormDefault="qualified">
  <xs:element name="root" type="rootElemType"/>
  <xs:complexType name="rootElemType">
    <xs:sequence>
      <xs:element ref="attr" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="attr" type="attrElemType"/>
  <xs:complexType name="attrElemType">
    <xs:sequence>
      <xs:element ref="interpretation" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:element name="interpretation" type="interPretationElemType"/>
  <xs:complexType name="interPretationElemType" mixed="true">
    <xs:choice minOccurs="0">
      <xs:element ref="style" maxOccurs="unbounded" minOccurs="1"/>
    </xs:choice>
    <xs:attribute ref="use" use="required"/>
    <xs:attribute name="context" use="optional" type="xs:anyURI"/>
  </xs:complexType>
  <xs:element name="style" type="styleElemType"/>
  <xs:complexType name="styleElemType">
    <!-- <xs:sequence>
      <xs:element name="key"/>
      <xs:element name="value"/>
    </xs:sequence> -->
    <xs:attribute name="key" use="required" type="xs:string"/>
    <xs:attribute name="value" use="required" type="xs:string"/>
  </xs:complexType>
  <xs:attribute name="use" type="useAttType"/>
  <xs:simpleType name="useAttType">
    <xs:restriction base="xs:NMTOKEN">
      <xs:enumeration value="default"/>
      <xs:enumeration value="abbreviation"/>
      <xs:enumeration value="extension"/>
      <xs:enumeration value="code"/>
      <xs:enumeration value="css"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== ferdisap/mpub/src/Config/Interpret/caption.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../assets/schemas/interpretation.xsd">
  <attr name="caption" value="co01">
    <interpretation use="css">
      <style>
        <key>background-color</key>
        <value>green</value>
      </style>
      <style>
        <key>color</key>
        <value>black</value>
      </style>
    </interpretation>
  </attr>
  <attr name="caption" value="co02">
    <interpretation use="css">
      <style>
        <key>background-color</key>
        <value>amber</value>
      </style>
      <style>
        <key>color</key>
        <value>black</value>
      </style>
    </interpretation>
  </attr>
  <attr name="caption" value="co03">
    <interpretation use="css">
      <style>
        <key>background-color</key>
        <value>yellow</value>
      </style>
      <style>
        <key>color</key>
        <value>black</value>
      </style>
    </interpretation>
  </attr>
  <attr name="caption" value="co04">
    <interpretation use="css">
      <style>
        <key>background-color</key>
        <value>red</value>
      </style>
      <style>
        <key>color</key>
        <value>black</value>
      </style>
    </interpretation>
  </attr>
  <attr name="caption" value="co07">
    <interpretation use="css">
      <style>
        <key>background-color</key>
        <value>white</value>
      </style>
      <style>
        <key>color</key>
        <value>black</value>
      </style>
    </interpretation>
  </attr>
  <attr name="caption" value="co08">
    <interpretation use="css">
      <style>
        <key>background-color</key>
        <value>grey</value>
      </style>
      <style>
        <key>color</key>
        <value>black</value>
      </style>
    </interpretation>
  </attr>
  <attr name="caption" value="co62">
    <interpretation use="css">
      <style>
        <key>background-color</key>
        <value>yellow</value>
      </style>
      <style>
        <key>color</key>
        <value>white</value>
      </style>
    </interpretation>
  </attr>
  <attr name="caption" value="co66">
    <interpretation use="css">
      <style>
        <key>background-color</key>
        <value>red</value>
      </style>
      <style>
        <key>color</key>
        <value>black</value>
      </style>
    </interpretation>
  </attr>
  <attr name="caption" value="co67">
    <interpretation use="css">
      <style>
        <key>background-color</key>
        <value>red</value>
      </style>
      <style>
        <key>color</key>
        <value>white</value>
      </style>
    </interpretation>
  </attr>
  <attr name="caption" value="co81">
    <interpretation use="css">
      <style>
        <key>background-color</key>
        <value>black</value>
      </style>
      <style>
        <key>color</key>
        <value>yellow</value>
      </style>
    </interpretation>
  </attr>
  <attr name="caption" value="co82">
    <interpretation use="css">
      <style>
        <key>background-color</key>
        <value>black</value>
      </style>
      <style>
        <key>color</key>
        <value>white</value>
      </style>
    </interpretation>
  </attr>
  <attr name="caption" value="co83">
    <interpretation use="css">
      <style>
        <key>background-color</key>
        <value>black</value>
      </style>
      <style>
        <key>color</key>
        <value>red</value>
      </style>
    </interpretation>
  </attr>
  <attr name="caption" value="co84">
    <interpretation use="css">
      <style>
        <key>background-color</key>
        <value>black</value>
      </style>
      <style>
        <key>color</key>
        <value>green</value>
      </style>
    </interpretation>
  </attr>
  <attr name="caption" value="co85">
    <interpretation use="css">
      <style>
        <key>background-color</key>
        <value>black</value>
      </style>
      <style>
        <key>color</key>
        <value>amber</value>
      </style>
    </interpretation>
  </attr>
</root>

=== ferdisap/mpub/src/Config/Interpret/controlAuth.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../assets/schemas/interpretation.xsd">
  <attr name="controlAuthorityType" value="cat01">
    <interpretation use="abbreviation">AD</interpretation>
  </attr>
  <attr name="controlAuthorityType" value="cat02">
    <interpretation use="abbreviation">AMOC</interpretation>
  </attr>
  <attr name="controlAuthorityType" value="cat03">
    <interpretation use="abbreviation">AWL</interpretation>
  </attr>
  <attr name="controlAuthorityType" value="cat04">
    <interpretation use="abbreviation">CATIII</interpretation>
  </attr>
  <attr name="controlAuthorityType" value="cat05">
    <interpretation use="abbreviation">CDCCL</interpretation>
  </attr>
  <attr name="controlAuthorityType" value="cat06">
    <interpretation use="abbreviation">CMR</interpretation>
  </attr>
  <attr name="controlAuthorityType" value="cat07">
    <interpretation use="abbreviation">ETOPS</interpretation>
  </attr>
  <attr name="controlAuthorityType" value="cat08">
    <interpretation use="abbreviation">EWIS</interpretation>
  </attr>
  <attr name="controlAuthorityType" value="cat09">
    <interpretation use="abbreviation">LOI</interpretation>
  </attr>
  <attr name="controlAuthorityType" value="cat10">
    <interpretation use="abbreviation">RII</interpretation>
  </attr>
  <attr name="controlAuthorityType" value="cat51">
    <interpretation use="abbreviation">DGCA</interpretation>
  </attr>
</root>

=== ferdisap/mpub/src/Config/Interpret/crewStepCondition.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../assets/schemas/interpretation.xsd">
  <attr name="crewStepCondition" value="csc01">
    <interpretation use="extension">Equipment is installed or available</interpretation>
  </attr>
  <attr name="crewStepCondition" value="csc02">
    <interpretation use="extension">A detailed procedure for the step is located in the performance section of the condensed checklists</interpretation>
  </attr>
  <attr name="crewStepCondition" value="csc03">
    <interpretation use="extension">Performance of the step is mandatory for all through-flights used for combat/tactical operations</interpretation>
  </attr>
  <attr name="crewStepCondition" value="csc04">
    <interpretation use="extension">A step that is mandatory for night flights</interpretation>
  </attr>
  <attr name="crewStepCondition" value="csc05">
    <interpretation use="extension">A task or step required by the operator's manual</interpretation>
  </attr>
</root>

=== ferdisap/mpub/src/Config/Interpret/color.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../assets/schemas/interpretation.xsd">
  <attr name="color" value="co01">
    <interpretation use="code">#14a339</interpretation>
  </attr>
  <attr name="color" value="co02">
    <interpretation use="code">#ffc107</interpretation>
  </attr>
  <attr name="color" value="co03">
    <interpretation use="code">#ffff00</interpretation>
  </attr>
  <attr name="color" value="co04">
    <interpretation use="code">#ff0000</interpretation>
  </attr>
  <attr name="color" value="co07">
    <interpretation use="code">#ffffff</interpretation>
  </attr>
  <attr name="color" value="co08">
    <interpretation use="code">#808080</interpretation>
  </attr>
  <attr name="color" value="co09">
    <interpretation use="code">#ffffff00</interpretation>
  </attr>
  <attr name="color" value="co09">
    <interpretation use="code">#00000</interpretation>
  </attr>
</root>

=== ferdisap/mpub/src/Config/Interpret/security.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../assets/schemas/interpretation.xsd">
  <attr name="securityClassification" value="01">
    <interpretation use="extension">unclassified</interpretation>
  </attr>
  <attr name="securityClassification" value="02">
    <interpretation use="extension">restricted</interpretation>
  </attr>
  <attr name="securityClassification" value="03">
    <interpretation use="extension">confidential</interpretation>
  </attr>
  <attr name="securityClassification" value="04">
    <interpretation use="extension">secret</interpretation>
  </attr>
  <attr name="securityClassification" value="05">
    <interpretation use="extension">top secret</interpretation>
  </attr>
</root>

=== ferdisap/mpub/src/Config/Interpret/maintenance.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../assets/schemas/interpretation.xsd">
  <attr name="sourceTypeCode" value="stc51">
    <interpretation use="abbreviation">MSG-3</interpretation>
  </attr>
  <attr name="sourceTypeCode" value="stc52">
    <interpretation use="abbreviation">ZAP</interpretation>
  </attr>
  <attr name="sourceTypeCode" value="stc53">
    <interpretation use="abbreviation">CMR</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th01">
    <interpretation use="abbreviation">FH</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th02">
    <interpretation use="abbreviation">FC</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th03">
    <interpretation use="extension">Months</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th04">
    <interpretation use="extension">Weeks</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th05">
    <interpretation use="extension">Years</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th06">
    <interpretation use="extension">Days</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th07">
    <interpretation use="extension">Supersonic Cycles</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th08">
    <interpretation use="extension">Pressure Cycles</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th09">
    <interpretation use="extension">Engine Cycles</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th10">
    <interpretation use="extension">Engine Change</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th11">
    <interpretation use="extension">Shop Visits</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th12">
    <interpretation use="extension">APU Change</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th13">
    <interpretation use="extension">Landing Gear Change</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th14">
    <interpretation use="extension">Wheel Change</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th15">
    <interpretation use="extension">Engine Start</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th16">
    <interpretation use="extension">APU Hours</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th17">
    <interpretation use="abbreviation">EH</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th18">
    <interpretation use="abbreviation">ETH</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th19">
    <interpretation use="extension">Landings</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th20">
    <interpretation use="extension">Operating Cycles</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th21">
    <interpretation use="extension">Operating hours</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th22">
    <interpretation use="extension">Supersonic hours</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th23">
    <interpretation use="extension">A</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th24">
    <interpretation use="extension">B</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th25">
    <interpretation use="extension">C</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th26">
    <interpretation use="extension">D</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th27">
    <interpretation use="extension">Daily</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th28">
    <interpretation use="extension">E</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th29">
    <interpretation use="extension">Overnight</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th30">
    <interpretation use="extension">Preflight</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th31">
    <interpretation use="extension">Routine</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th32">
    <interpretation use="extension">Structural C Check</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th33">
    <interpretation use="extension">Service Check</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th34">
    <interpretation use="extension">Transit</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th35">
    <interpretation use="extension">Kilometers</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th36">
    <interpretation use="extension">cubic meter</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th37">
    <interpretation use="extension">l</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th38">
    <interpretation use="extension">shots</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th39">
    <interpretation use="extension">shots</interpretation>
  </attr>
  <attr name="thresholdUnitOfMeasure" value="th51">
    <interpretation use="extension">-Z-</interpretation>
  </attr>
  <attr name="taskCode" value="taskcd01">
    <interpretation use="abbreviation">DET</interpretation>
  </attr>
  <attr name="taskCode" value="taskcd02">
    <interpretation use="abbreviation">DS</interpretation>
  </attr>
  <attr name="taskCode" value="taskcd03">
    <interpretation use="abbreviation">FC</interpretation>
  </attr>
  <attr name="taskCode" value="taskcd04">
    <interpretation use="abbreviation">GVI</interpretation>
  </attr>
  <attr name="taskCode" value="taskcd05">
    <interpretation use="abbreviation">LU</interpretation>
  </attr>
  <attr name="taskCode" value="taskcd06">
    <interpretation use="abbreviation">OP</interpretation>
  </attr>
  <attr name="taskCode" value="taskcd07">
    <interpretation use="abbreviation">RS</interpretation>
  </attr>
  <attr name="taskCode" value="taskcd08">
    <interpretation use="abbreviation">SV</interpretation>
  </attr>
  <attr name="taskCode" value="taskcd09">
    <interpretation use="abbreviation">IN</interpretation>
  </attr>
  <attr name="taskCode" value="taskcd10">
    <interpretation use="abbreviation">SDI</interpretation>
  </attr>
</root>
