=== ferdisap/mpub/assets/schemas/interpretation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="qualified" elementFormDefault="qualified">
  <xs:element name="root" type="rootElemType"/>
  <xs:complexType name="rootElemType">
    <xs:sequence>
      <xs:element ref="attr" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="attr" type="attrElemType"/>
  <xs:complexType name="attrElemType">
    <xs:sequence>
      <xs:element ref="interpretation" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="value" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:element name="interpretation" type="interPretationElemType"/>
  <xs:complexType name="interPretationElemType" mixed="true">
    <xs:choice minOccurs="0">
      <xs:element ref="style" maxOccurs="unbounded" minOccurs="1"/>
    </xs:choice>
    <xs:attribute ref="use" use="required"/>
    <xs:attribute name="context" use="optional" type="xs:anyURI"/>
  </xs:complexType>
  <xs:element name="style" type="styleElemType"/>
  <xs:complexType name="styleElemType">
    <!-- <xs:sequence>
      <xs:element name="key"/>
      <xs:element name="value"/>
    </xs:sequence> -->
    <xs:attribute name="key" use="required" type="xs:string"/>
    <xs:attribute name="value" use="required" type="xs:string"/>
  </xs:complexType>
  <xs:attribute name="use" type="useAttType"/>
  <xs:simpleType name="useAttType">
    <xs:restriction base="xs:NMTOKEN">
      <xs:enumeration value="default"/>
      <xs:enumeration value="abbreviation"/>
      <xs:enumeration value="extension"/>
      <xs:enumeration value="code"/>
      <xs:enumeration value="css"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== ferdisap/mpub/src/Config/Interpret/frontMatter.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../assets/schemas/interpretation.xsd">
  <attr name="frontMatterType" value="fm01">
    <interpretation use="abbreviation">leop</interpretation>
  </attr>
  <attr name="frontMatterType" value="fm02">
    <interpretation use="abbreviation">leodm</interpretation>
  </attr>
  <attr name="frontMatterType" value="fm03">
    <interpretation use="abbreviation">highlights</interpretation>
  </attr>
  <attr name="frontMatterType" value="fm04">
    <interpretation use="abbreviation">highlights and updating instruction</interpretation>
  </attr>
  <attr name="frontMatterType" value="fm05">
    <interpretation use="abbreviation">publication list data modules</interpretation>
  </attr>
  <attr name="frontMatterType" value="fm06">
    <interpretation use="abbreviation">loi</interpretation>
  </attr>
  <attr name="frontMatterType" value="fm07">
    <interpretation use="abbreviation">loa</interpretation>
  </attr>
  <attr name="frontMatterType" value="fm08">
    <interpretation use="abbreviation">lot</interpretation>
  </attr>
  <attr name="frontMatterType" value="fm09">
    <interpretation use="abbreviation">los</interpretation>
  </attr>
  <attr name="frontMatterType" value="fm10">
    <interpretation use="abbreviation">tsr</interpretation>
  </attr>
  <attr name="frontMatterType" value="fm11">
    <interpretation use="abbreviation">lom</interpretation>
  </attr>
  <attr name="frontMatterType" value="fm12">
    <interpretation use="abbreviation">loasd</interpretation>
  </attr>
  <attr name="frontMatterType" value="fm13">
    <interpretation use="abbreviation">low</interpretation>
  </attr>
  <attr name="frontMatterType" value="fm14">
    <interpretation use="abbreviation">loc</interpretation>
  </attr>
  <attr name="frontMatterType" value="fm15">
    <interpretation use="abbreviation">lose</interpretation>
  </attr>
  <attr name="frontMatterType" value="fm16">
    <interpretation use="abbreviation">losu</interpretation>
  </attr>
  <attr name="frontMatterType" value="fm17">
    <interpretation use="abbreviation">losp</interpretation>
  </attr>
  <attr name="frontMatterType" value="fm18">
    <interpretation use="abbreviation">lov</interpretation>
  </attr>
</root>

=== ferdisap/mpub/src/Config/Interpret/skillType.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../assets/schemas/interpretation.xsd">
  <attr name="skillType" value="st01">
    <interpretation use="abbreviation">AIRPL</interpretation>
  </attr>
  <attr name="skillType" value="st02">
    <interpretation use="abbreviation">ELEC</interpretation>
  </attr>
  <attr name="skillType" value="st03">
    <interpretation use="abbreviation">AVION</interpretation>
  </attr>
  <attr name="skillType" value="st04">
    <interpretation use="abbreviation">ENGIN</interpretation>
  </attr>
</root>

=== ferdisap/mpub/src/Config/Interpret/textElement.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../assets/schemas/interpretation.xsd">
  <attr name="emphasisType" value="em01">
    <interpretation use="extension">bold</interpretation>
  </attr>
  <attr name="emphasisType" value="em02">
    <interpretation use="extension">italic</interpretation>
  </attr>
  <attr name="emphasisType" value="em03">
    <interpretation use="extension">underline</interpretation>
  </attr>
  <attr name="emphasisType" value="em05">
    <interpretation use="extension">strikethrough</interpretation>
  </attr>
  <attr name="emphasisType" value="em06">
    <interpretation use="extension">underline-bold</interpretation>
  </attr>
  <attr name="emphasisType" value="em07">
    <interpretation use="extension">underline-italic</interpretation>
  </attr>
  <attr name="emphasisType" value="em08">
    <interpretation use="extension">bold-italic</interpretation>
  </attr>
  <attr name="emphasisType" value="em09">
    <interpretation use="extension">bold-italic-underline</interpretation>
  </attr>
</root>

=== ferdisap/mpub/src/Config/Interpret/pm.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../assets/schemas/interpretation.xsd">
  <attr name="pmType" value="pt01">
    <interpretation use="abbreviation">cmm</interpretation>
  </attr>
  <attr name="pmType" value="pt02">
    <interpretation use="abbreviation">ipd</interpretation>
  </attr>
  <attr name="pmType" value="pt03">
    <interpretation use="abbreviation">sb</interpretation>
  </attr>
  <attr name="pmType" value="pt51">
    <interpretation use="abbreviation">poh</interpretation>
  </attr>
  <attr name="pmType" value="pt52">
    <interpretation use="abbreviation">maintPlanning</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt01">
    <interpretation use="abbreviation">TP</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt02">
    <interpretation use="abbreviation">CONF</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt03">
    <interpretation use="abbreviation">COPY</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt04">
    <interpretation use="abbreviation">ADMIN</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt05">
    <interpretation use="abbreviation">SAFE</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt06">
    <interpretation use="abbreviation">LOEDM</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt07">
    <interpretation use="abbreviation">CR</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt08">
    <interpretation use="abbreviation">HIGH</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt09">
    <interpretation use="abbreviation">LOA</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt10">
    <interpretation use="abbreviation">LOT</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt11">
    <interpretation use="abbreviation">LOS</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt12">
    <interpretation use="abbreviation">TSR</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt13">
    <interpretation use="abbreviation">TOC</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt14">
    <interpretation use="abbreviation">LOI</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt15">
    <interpretation use="abbreviation">LOTBL</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt16">
    <interpretation use="abbreviation">LOASD</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt17">
    <interpretation use="abbreviation">LOSUP</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt18">
    <interpretation use="abbreviation">LOSE</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt19">
    <interpretation use="abbreviation">LOSU</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt20">
    <interpretation use="abbreviation">LOSP</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt21">
    <interpretation use="abbreviation">INTRO</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt22">
    <interpretation use="abbreviation">FUNC</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt23">
    <interpretation use="abbreviation">DESC</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt24">
    <interpretation use="abbreviation">SCHEM</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt25">
    <interpretation use="abbreviation">MAINT</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt26">
    <interpretation use="abbreviation">RI</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt27">
    <interpretation use="abbreviation">TS</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt28">
    <interpretation use="abbreviation">SERVC</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt29">
    <interpretation use="abbreviation">TEST</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt30">
    <interpretation use="abbreviation">DIS</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt31">
    <interpretation use="abbreviation">REP</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt32">
    <interpretation use="abbreviation">ASSY</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt33">
    <interpretation use="abbreviation">STORE</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt34">
    <interpretation use="abbreviation">IPD</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt51">
    <interpretation use="abbreviation">Structure Inspection Program</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt52">
    <interpretation use="abbreviation">System And Powerplant Inspection Program</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt53">
    <interpretation use="abbreviation">Zonal Inspection Program</interpretation>
  </attr>
  <attr name="pmEntryType" value="pmt54">
    <interpretation use="abbreviation">Time Limit Program</interpretation>
  </attr>
  <!-- seperti AMM CHP5 CN235 chapter 05-20-20 -->
  <!-- seperti AMM CHP5 CN235 chapter 05-20-10 -->
  <!-- seperti AMM CHP5 CN235 chapter 05-20-30 -->
  <!-- seperti AMM CHP5 CN235 chapter 05-10-10 -->
</root>

=== ferdisap/mpub/src/Config/Interpret/icnInfoItemType.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../assets/schemas/interpretation.xsd">
  <attr name="icnInfoItemType" value="iiit01">
    <interpretation use="default">Unspecified</interpretation>
  </attr>
  <attr name="icnInfoItemType" value="iiit02">
    <interpretation use="default">Size (kb)</interpretation>
  </attr>
  <attr name="icnInfoItemType" value="iiit03">
    <interpretation use="default">Size (kb)</interpretation>
  </attr>
  <attr name="icnInfoItemType" value="iiit04">
    <interpretation use="default">Duration (s)</interpretation>
  </attr>
  <attr name="icnInfoItemType" value="iiit05">
    <interpretation use="default">Width (mm)</interpretation>
  </attr>
  <attr name="icnInfoItemType" value="iiit06">
    <interpretation use="default">Transcript</interpretation>
  </attr>
</root>

=== ferdisap/mpub/src/Config/Interpret/crewMember.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../assets/schemas/interpretation.xsd">
  <attr name="crewMemberType" value="cm01">
    <interpretation use="extension">All</interpretation>
  </attr>
  <attr name="crewMemberType" value="cm02">
    <interpretation use="extension">Pilot</interpretation>
  </attr>
  <attr name="crewMemberType" value="cm03">
    <interpretation use="extension">Co-Pilot</interpretation>
  </attr>
  <attr name="crewMemberType" value="cm04">
    <interpretation use="extension">Navigator</interpretation>
  </attr>
  <attr name="crewMemberType" value="cm05">
    <interpretation use="extension">Engineer</interpretation>
  </attr>
  <attr name="crewMemberType" value="cm06">
    <interpretation use="extension">Ground Crew</interpretation>
  </attr>
  <attr name="crewMemberType" value="cm07">
    <interpretation use="extension">Load Master</interpretation>
  </attr>
  <attr name="crewMemberType" value="cm08">
    <interpretation use="extension">Cabin Spv.</interpretation>
  </attr>
  <attr name="crewMemberType" value="cm51">
    <interpretation use="extension">CM1</interpretation>
  </attr>
  <attr name="crewMemberType" value="cm52">
    <interpretation use="extension">CM2</interpretation>
  </attr>
  <attr name="crewMemberType" value="cm53">
    <interpretation use="extension">CM3</interpretation>
  </attr>
  <attr name="crewMemberType" value="cm54">
    <interpretation use="extension">Pil1</interpretation>
  </attr>
  <attr name="crewMemberType" value="cm55">
    <interpretation use="extension">Pil2</interpretation>
  </attr>
  <attr name="crewMemberType" value="cm56">
    <interpretation use="extension">Pil3</interpretation>
  </attr>
  <attr name="crewMemberType" value="cm57">
    <interpretation use="extension">Pil4</interpretation>
  </attr>
  <attr name="crewMemberType" value="cm58">
    <interpretation use="extension">MO</interpretation>
  </attr>
  <attr name="crewMemberType" value="cm59">
    <interpretation use="extension">LM</interpretation>
  </attr>
  <attr name="crewMemberType" value="cm60">
    <interpretation use="extension">T</interpretation>
  </attr>
</root>

=== ferdisap/mpub/src/Config/Interpret/comment.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../assets/schemas/interpretation.xsd">
  <attr name="enterpriseCode" value="0001Z">
    <interpretation use="abbreviation">PTDI</interpretation>
    <interpretation use="extension">PT. Dirgantara Indonesia1</interpretation>
  </attr>
  <attr name="commentPriorityCode" value="cp01">
    <interpretation use="extension">Routine</interpretation>
  </attr>
  <attr name="commentPriorityCode" value="cp02">
    <interpretation use="extension">Emergency</interpretation>
  </attr>
  <attr name="commentPriorityCode" value="cp03">
    <interpretation use="extension">Safety critical</interpretation>
  </attr>
  <attr name="responseType" value="rt01">
    <interpretation use="extension">Accepted</interpretation>
  </attr>
  <attr name="responseType" value="rt02">
    <interpretation use="extension">Pending</interpretation>
  </attr>
  <attr name="responseType" value="rt03">
    <interpretation use="extension">Partly</interpretation>
  </attr>
  <attr name="responseType" value="rt04">
    <interpretation use="extension">Rejected</interpretation>
  </attr>
</root>

=== ferdisap/mpub/src/Config/Interpret/internalRef.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../assets/schemas/interpretation.xsd">
  <attr name="internalRefTargetType" value="irtt01">
    <interpretation use="extension">figure</interpretation>
  </attr>
  <attr name="internalRefTargetType" value="irtt02">
    <interpretation use="extension">table</interpretation>
  </attr>
  <attr name="internalRefTargetType" value="irtt03">
    <interpretation use="extension">multimedia</interpretation>
  </attr>
  <attr name="internalRefTargetType" value="irtt04">
    <interpretation use="extension">supply</interpretation>
  </attr>
  <attr name="internalRefTargetType" value="irtt05">
    <interpretation use="extension">support Equipment</interpretation>
  </attr>
  <attr name="internalRefTargetType" value="irtt06">
    <interpretation use="extension">spare</interpretation>
  </attr>
  <attr name="internalRefTargetType" value="irtt07">
    <interpretation use="extension">para</interpretation>
  </attr>
  <attr name="internalRefTargetType" value="irtt08">
    <interpretation use="extension">step</interpretation>
  </attr>
  <attr name="internalRefTargetType" value="irtt10">
    <interpretation use="extension">multimedia</interpretation>
  </attr>
  <attr name="internalRefTargetType" value="irtt11">
    <interpretation use="extension">zone</interpretation>
  </attr>
  <attr name="internalRefTargetType" value="irtt14">
    <interpretation use="extension">work area</interpretation>
  </attr>
  <attr name="internalRefTargetType" value="irtt15">
    <interpretation use="extension">SB</interpretation>
  </attr>
  <attr name="internalRefTargetType" value="irtt16">
    <interpretation use="extension">access</interpretation>
  </attr>
</root>
